Added logger debug
Lenders-Cooperative/Django-DocuSign pull request #4
Opened 2022-01-19 18:04 UTC by k-shailesh

PR for logging logic

2022-01-19 18:24 UTC, GoelJatin requested changes

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/api_handler.py
>          self.extra_headers = {}
We're not using extra_headers or connection_exceptions anywhere anymore

Ref: https://github.com/Lenders-Cooperative/CSCRecorder/blob/master/csc_recorder/APIHandler.py, https://github.com/Lenders-Cooperative/scex_py/blob/main/scex_py/api_handler.py

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/api_handler.py
> +    def send_request(self, method, params=None, payload=None, log_config: dict = None, extra_headers=None):
extra_headers is not being set in the request headers, if it is ever passed

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/api_handler.py
> +            if self.__logging:
why are we not raising the exception after catching and logging it?

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/api_handler.py
> +            #    f"Exception while connecting to DocuSign : {excp}. Response Body: {response.text}"
remove all the code smell (commented sections)

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/client.py
>          if not (
I don't think this condition works the way you guys want it to

@k-shailesh @tejasb

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/client.py
> +            LOGGER.error("Invalid input dict for generate_docusign_preview_url")
we should still raise exception, otherwise it'd cause failures later on

2022-01-19 18:24 UTC, GoelJatin commented on los_docusign/utils/docusign_helper.py
> +        raise
@tejasb , is it okay to raise exception from here or do you still need string

basically this would require changes in the LOS code as well from where we're calling this

Ideally we should raise

2022-01-19 18:26 UTC, GoelJatin commented on los_docusign/utils/client.py
>          docusign_handler = ApiHandler(preview_url, self.api_key)
if your request url always changes then your ApiHandler should itself change and accept request url in send_request and not in the class init

we shouldn't keep on creating ApiHandler objects for every API call

2022-01-20 11:36 UTC, tejasb approved these changes
Looks good to me

2022-01-20 11:37 UTC, merged